### ISSUE TITLE
ControlIn commands must return length of data received

### ISSUE THREAD

**Issue by GoogleCodeExporter** [madwizard-thomas/winusbnet#12]
ControlIn USB commands must return the number of bytes that were actually 
received. 

In typical USB applications its common to have bulk transfers where you don't 
know the length of the data that you're going to receive - so you set up a 
buffer with the maximum possible bytes and execute a ControlIn(..., buffer) 
command. After the command you check to see how many bytes were actually 
received.

Original issue reported on code.google.com by `navneet....@gmail.com` on 24 Feb 2015 at 12:19

**Comment by madwizard-thomas** [comment]
The functions probably should return the number of bytes received, even though most control transfers use a fixed length. Changing this may break existing programs in some cases though, I would have to check this.

**Comment by dnguye86** [comment]
Are you gonna address this issue anytime soon? I'm using control in transfer and the ability to know exactly how much data I receive from the device would be greatly appreciated.

**Comment by adadurov** [comment]
@madwizard-thomas , I can work on a pull request to fix it. Are you interested?
If yes, which of the two options would you prefer?

1. Release entirely new version with a 'breaking change' -- so that existing users will need to fix their apps in order to upgrade to the new version.

public void ControlIn(byte requestType, byte request, int value, int index, byte[] buffer);
becomes
**public int ControlIn(byte requestType, byte request, int value, int index, byte[] buffer);**

public void ControlIn(byte requestType, byte request, int value, int index, byte[] buffer, int length);
becomes
**public int ControlIn(byte requestType, byte request, int value, int index, byte[] buffer, int length);**

public byte[] ControlIn(byte requestType, byte request, int value, int index, int length);
**will return the array of bytes, with the size equal to the number of bytes received**

2. Fix it a somewhat ugly but client-friendly way -- adding an additional overloads for ControLIn method (with the last parameter being 'out int received') and adding 'deprecated' attribute to the existing functions that should be replaced. The 3 existing overloads will still be preserved:

public void ControlIn(byte requestType, byte request, int value, int index, byte[] buffer);
public void ControlIn(byte requestType, byte request, int value, int index, byte[] buffer, int length);
public byte[] ControlIn(byte requestType, byte request, int value, int index, int length);

**and new overloads are added, as below:**
public void ControlIn(byte requestType, byte request, int value, int index, byte[] buffer**, out int received**);
public void ControlIn(byte requestType, byte request, int value, int index, byte[] buffer, int length**, out int received**);
public byte[] ControlIn(byte requestType, byte request, int value, int index, int length**, out int received**);

**Comment by madwizard-thomas** [comment]
Yes, that would be great! I prefer releasing a new version and fixing it properly, so option 1.

**Comment by adadurov** [comment]
Hello @madwizard-thomas , please check it: https://github.com/madwizard-thomas/winusbnet/pull/28.

**Comment by madwizard-thomas** [comment]
Hi, thanks for the changes! It looks fine to me, I'll just have to find the time to check it and build a new release. Have you tested them with real hardware as well?

**Comment by adadurov** [comment]
Yes, I tested the changes with the new X20 device that I work on here: https://github.com/adadurov/PskOnline.X20.Firmware
