### ISSUE TITLE
How to install WinUSB driver through customized inf file on Windows 10?

### ISSUE THREAD

**Issue by Penetrator80** [madwizard-thomas/winusbnet#20]
I need to communicate with a simple custom device directly through USB. I have full specifications for communication protocol. Unfortunately, the device vendor did not provide WinUSB driver for the device.

According to https://msdn.microsoft.com/en-us/library/ff540283.aspx#inf I should be able to install WinUSB driver automatically on Windows 10 using the inf template.

But installation fails with:

The third-party INF does not contain digital signature information.
As I understand, it is looking for a signed .cat file. But in this case I have no any files to sign nor .cat file. I just want to install Windows own WinUSB driver for the device, and clearly Windows drivers should be signed by Microsoft.

How do I proceed to install the .inf file?

**Comment by madwizard-thomas** [comment]
Each version of windows the signing requirements got stricter. For vista and windows 7 you could use an unsigned .inf file because the driver code itself was signed by Microsoft, even though you had to click through a warning. Starting with windows 8 the .inf (.cat) needs to be signed as well (not necessarily by microsoft). For your own hobby projects I can recommend Zadig (http://zadig.akeo.ie/), which signs a driver with a dummy certificate and adds this dummy certificate to your windows root certificates so your system will accept the self signed signature.
